#!/bin/bash

set -euo pipefail

cname=cli
in_container="toolbox run --container $cname"

# Takes arguments:
# 1: name of container
# 2..n: packages to install
function create_toolbox {
  local cname="$1"
  shift
  (
    set -x
    toolbox create "$cname" 2>/dev/null
    $in_container sudo dnf install -y "$@"
  ) || true
}

# Check if we are outside the container:

if [[ "${1:-}" != "--inside-container" ]]; then
  packages=(fzf bat)
  create_toolbox "$cname" "${packages[@]}"

  set -x
  exec $in_container "$0" --inside-container "$@"
fi

# We should now be inside the container.
shift

cwd="$(dirname "$0")"
package_utils="$cwd/package-utils.sh"
config_dir="$cwd/cli.d"
source_run=$(which "$HOME"/bin/,source-some-scripts)

source "$package_utils"

# Can/will be used by sourced config scripts:
# shellcheck disable=SC2034
#fedora_version=${1:-$(rpm -E %fedora)}

###############################################################################

title "Parsing configs..."
source "$source_run" "$config_dir"/*.sh

###############################################################################

repository_add_exec

dnf_remove_exec
dnf_install_exec

yarn_add_exec

post_run_add_exec "$config_dir"

echo "Done."
