#!/bin/bash

set -euo pipefail

cname=rust
in_container="toolbox run --container $cname"

scripts_dir=$(readlink -e rust.d)
run_scripts_from=$(which ,run-scripts-from)

packages=(
  fzf bat
)

function create_toolbox {
  (
    set -x
    toolbox create $cname 2>/dev/null
    $in_container sudo dnf install -y "${packages[@]}"
  ) || true
}

create_toolbox

set -x
exec $in_container "$run_scripts_from" "$scripts_dir" "$@"
