# from https://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# reload config file
bind r source-file ~/.config/tmux/tmux.conf \\; display "config Reloaded"

# Enable mouse control (clickable windows, panes, resizable panes)
# set -g mouse-select-window on
# set -g mouse-select-pane on
# set -g mouse-resize-pane on

# Enable mouse mode (tmux 2.1 and above)
# Turn the mouse on, but without copy mode dragging
set -g mouse on
#unbind -n MouseDrag1Pane
#unbind -Tcopy-mode MouseDrag1Pane

# remove delay when hitting escape (which is quite annoying when using vim)
# https://stackoverflow.com/a/13843382
set -s escape-time 1

###############################################################################
# Visuals
###############################################################################

set -g status-left-length 40
set -g status-right-length 60

# remove hostname and clock on the right side:
#set -g status-right ''
set -g status-right '#(gitmux -cfg $HOME/.config/tmux/gitmux.conf "#{pane_current_path}")'


###############################################################################
# tpm tmux plugin manager
# https://github.com/tmux-plugins/tpm
###############################################################################

# Config files for plugins:
run-shell 'for f in ~/.config/tmux/conf.d/*.conf; do tmux source-file "$f"; done'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# Install first:
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
run '~/.tmux/plugins/tpm/tpm'
