#!/bin/bash

# https://docs.cloud.google.com/sdk/docs/install-sdk#rpm

set -euo pipefail

packages+=(
  libxcrypt-compat.x86_64
  google-cloud-cli
)

# https://learn.microsoft.com/en-us/mem/intune/user-help/microsoft-intune-app-linux#install-microsoft-intune-app-for-redhat-enterprise-linux
#sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
#sudo dnf config-manager --add-repo https://packages.microsoft.com/yumrepos/microsoft-rhel9.0-prod

repo_filename="google-cloud-cli.repo"
repo_url="$(realpath ./local-sway.d/google-cloud-cli.repo)"

#repos[$repo_filename]="$repo_url"

# copy manually since we're not using curl:
output="/etc/yum.repos.d/$repo_filename"
subtitle "$output from $repo_url"
sudo cp -vi "$repo_url" "$output"
