#!/bin/bash

set -euo pipefail

# sway base with (only) infinite scroll
# https://github.com/dawsers/scroll

packages+=(
  scroll
)

repo_filename="_copr:copr.fedorainfracloud.org:scrollwm.repo"
repo_url="https://copr.fedorainfracloud.org/coprs/scrollwm/packages/repo/fedora-${fedora_version}/scrollwm-packages-fedora-${fedora_version}.repo"

repos[$repo_filename]="$repo_url"
