icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
#[icons.overrides]
#bat = ["|E|", "|_|", "|=|", "|F|"]
#bat_charging = "|^| "

[[block]]
block = "bluetooth"
mac = "4C:87:5D:52:CB:5F"

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

[[block]]
block = "net"
device = "tun0"
missing_format = ""

[[block]]
block = "net"
#device = "wlp3s0"
#device = "wlp1s0"
format = " $icon {$ssid $signal_strength|Wired connection}"
format_alt = " $icon { $device$frequency $ssid $signal_strength|Wired connection}"

[[block]]
block = "memory"
#format = " $icon $mem_total_used_percents.eng(w:2) "
#format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
format = " $icon $mem_used_percents.eng(w:2) "
format_alt = " $icon $mem_used.eng(w:4) $mem_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 1
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
format = " $icon $utilization "
format_alt = " $icon $barchart {$boost |}$frequency $utilization "

[[block]]
block = "temperature"
interval = 10
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
chip = "*-isa-*"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = ",pavucontrol"

[[block]]
block = "backlight"
invert_icons = true
missing_format = ""

[[block]]
block = "battery"
#driver = "upower"
interval = 1
format = "{ $icon |}{ $time |}$percentage "
missing_format = ""

[[block]]
block = "time"
interval = 1
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d/%m %H:%M:%S') "
short = " $icon $timestamp.datetime(f:'%H:%M') "
