# show directory instead of shell for these names:
set -g @tmux_window_name_shells "['bash', 'fish', 'sh', 'zsh', 'toolbox', ',cli']"
# show directory plus program for these names:
set -g @tmux_window_dir_programs "['nvim', 'vim', 'vi', 'git']"
#set -g @tmux_window_dir_programs "['git', ',cli']"
set -g @tmux_window_name_use_tilde "True"
set -g @tmux_window_name_show_program_args "False"

# automatically better window names
set -g @plugin 'ofirgall/tmux-window-name'
