#!/bin/bash

set -euo pipefail

fedora_packages=(
    com.github.tchx84.Flatseal
    org.gnome.Calculator
    org.gnome.Shotwell
)

flathub_packages=(
    com.google.Chrome
    com.obsproject.Studio
    com.vscodium.codium
    com.yubico.yubioath
    io.mpv.Mpv
    org.gnome.Snapshot
    org.inkscape.Inkscape
    org.libvips.vipsdisp
    org.mozilla.firefox
    org.pencil2d.Pencil2D
)

(
  set -x

  flatpak install -y fedora "${fedora_packages[@]}"

  flatpak install -y flathub "${flathub_packages[@]}"
)
