#!/bin/bash

set -euo pipefail

packages=(
  brightnessctl
  pamixer

  dex-autostart
  lxpolkit
  zenity

  tmux
)

packages_remove=()

# associative map (dictionary):
declare -A repos
declare -A packages_override
declare -A packages_replace

fedora_version=$(rpm -E %fedora)

rpm_config_dir=~/scripts/rpm.d

if [ -d "$rpm_config_dir" ]; then
    for part in "$rpm_config_dir"/*.conf; do
        if [ -f "$part" ]; then
            echo "Running $part ..."
            . "$part"
        fi
    done
fi
unset part

###############################################################################

echo -e "\nInstalling repositories..."
for repo_filename in ${!repos[@]}; do
    repo_url=${repos[$repo_filename]}
    output="/etc/yum.repos.d/$repo_filename"
    echo "$output from $repo_url"
    sudo curl --progress-bar --location --output "$output" "$repo_url"
done
unset repo_filename repo_url output

echo -e "\nRemoving packages..."
for package in ${packages_remove[@]}; do
    (
        set -x
        rpm-ostree override remove "${package}"
    ) || true
done
unset package

echo -e "\nAdding packages..."
(
    set -x
    rpm-ostree install --idempotent -y "${packages[@]}"
)

echo -e "\nOverriding specific packages..."
for remove_package in ${!packages_override[@]}; do
    add_package=${packages_override[$remove_package]}
    (
        set -x
        rpm-ostree override remove "$remove_package" --install "$add_package"
    ) || true
done
unset remove_package add_package

echo -e "\nReplacing specific packages..."
for remove_package in ${!packages_replace[@]}; do
    add_package=${packages_replace[$remove_package]}
    (
        set -x
        rpm-ostree update --uninstall "$remove_package" --install "$add_package"
    ) || true
done
unset remove_package add_package

echo -e "\nRunning post install scripts..."
if [ -d "$rpm_config_dir" ]; then
    for post in "$rpm_config_dir"/*.post; do
        if [ -f "$post" ]; then
            echo "Running $post ..."
            . "$post"
        fi
    done
fi
unset post

set -x
sudo rpm-ostree apply-live --allow-replacement
