#!/bin/bash

set -euo pipefail

prompt="Pick one of the base images to rebase to: "
arch=$(uname -m)
system_type=${1:-"${arch}/silverblue"}
shift

ref=$(ostree remote refs fedora|grep "$system_type"|fzf --prompt="$prompt" --height=10 --cycle --reverse --tac)

(
  set -x
  rpm-ostree rebase "$@" "$ref"
)
