#!/bin/bash

set -euo pipefail

conf_dir=$(dirname "$0")/local-config.d

function run_systemd_conf {
  systemd_root=/etc/systemd

  (
    cd "$conf_dir"/systemd

    for config_file in **/*; do
      destination=$(readlink --canonicalize-missing "$systemd_root/$config_file")
      subdir=$(dirname "$destination")
      [[ -d "$subdir" ]] || mkdir -vp "$subdir"

      cp -iv "$config_file" "$destination"
    done

    set -x
    systemctl reload systemd-logind
    systemctl daemon-reload
  )
  unset systemd_root destination subdir
}

function run_sysctl_conf {
  sysctl_root=/etc

  (
    cd "$conf_dir"/sysctl

    for config_file in **/*; do
      destination=$(readlink --canonicalize-missing "$sysctl_root/$config_file")
      subdir=$(dirname "$destination")
      [[ -d "$subdir" ]] || mkdir -vp "$subdir"

      cp -iv "$config_file" "$destination"
    done

    set -x
    sysctl -p
  )
  unset sysctl_root destination subdir
}

run_sysctl_conf
run_systemd_conf
