#!/bin/bash

set -euo pipefail

prompt="Pick one of the base images to rebase to: "
arch=$(uname -m)
system_type=${1:-"${arch}/silverblue"}
shift || true

(
  set -x
  ref=$(ostree remote refs fedora|grep "$system_type"|fzf --prompt="$prompt" --cycle --reverse --tac)
  exec rpm-ostree rebase "$@" "$ref"
)
