#!/bin/bash

set -euo pipefail

packages=(
  brightnessctl
  dex-autostart
  lxpolkit
  pamixer

  # fzf history search needs perl
  fzf perl
  tmux

  zenity
)

packages_remove=(
  firefox
  firefox-langpacks
)

fedora_version=$(rpm -E %fedora)

if [ -d ~/scripts/local-sway.d ]; then
    for part in ~/scripts/local-sway.d/*.part; do
        if [ -f "$part" ]; then
            echo "Adding $part ..."
            . "$part"
        fi
    done
fi
unset part

set -x

rpm-ostree override remove "${packages_remove[@]}" || true
rpm-ostree install --idempotent -y "${packages[@]}"

sudo rpm-ostree apply-live --allow-replacement
