#!/bin/bash

set -euo pipefail

fedora_packages=(
    com.github.tchx84.Flatseal
    org.gnome.Shotwell
    org.mozilla.Firefox
)

flathub_packages=(
    com.google.Chrome
    com.obsproject.Studio
    io.mpv.Mpv
)

set -x

flatpak install -y fedora "${fedora_packages[@]}"

flatpak install -y flathub "${flathub_packages[@]}"
