#!/bin/bash

set -euo pipefail

build_cname=build
build="toolbox run --container $build_cname"

scripts_dir=toolbox-build.d
fzf=$(which fzf)

function select_scripts {
  all_scripts=$(ls -1 "$scripts_dir"/*.sh)

  selected_scripts=$(echo "${all_scripts}" |
    $fzf --multi --reverse \
      --height=10 --prompt='Which scripts to run: ' \
      --preview='cat {}'
  )

  echo "$selected_scripts"
}

function run_scripts {
  for file in ${selected_scripts}; do
      echo "== Running $file..."
      if [ -x "$file" ]; then
        (
          set -x
          $build "$file"
        )
      fi
  done
  unset file
}

(
  set -x
  toolbox create $build_cname
) || true

select_scripts
run_scripts
