#!/bin/bash

set -euo pipefail

# text user interface
cname=cli
run="toolbox run --container $cname"

packages=(
  neovim vim fzf
  NetworkManager-tui
  nodejs yarnpkg
  keychain rclone
  jq entr
  # these give us ansi2txt for stripping color codes
  graphviz colorized-logs
  # convenience, wl-copy etc:
  wl-clipboard

  ripgrep

  # bashls:
  shellcheck
)

yarns=(
  bash-language-server
)

set -x

toolbox create $cname || true

$run sudo dnf install -y "${packages[@]}"
$run yarn global add "${yarns[@]}"
