#!/bin/bash

set -euo pipefail

cname=rust
run="toolbox run --container $cname"

packages=(
  neovim vim fzf
  keychain
  jq entr
  # these give us ansi2txt for stripping color codes:
  graphviz colorized-logs

  rust
)

set -x

toolbox create $cname 2>/dev/null || true

$run sudo dnf install -y "${packages[@]}"
