#!/bin/bash

set -euo pipefail

build_cname=build
run="toolbox run --container $build_cname"

scripts_dir=$(readlink -e toolbox-build.d)
run_scripts_from=$(which ./run-scripts-from)

dependencies=(
  fzf
)

function create_toolbox {
  (
    set -x
    toolbox create $build_cname 2>/dev/null
    $run sudo dnf install -y "${dependencies[@]}"
  ) || true
}

create_toolbox
$run "$run_scripts_from" "$scripts_dir" "$@"
