#!/bin/bash

set -euo pipefail

cname=gui
run="toolbox run --container $cname"

copr_i3status_rs="atim/i3status-rust"

# wdisplays needs libGLESv2 which in fedora is found in libglvnd-gles:
dnf_sway="wdisplays libglvnd-gles wf-recorder"
dnf_misc="i3status-rust gkrellm zenity"

set -x

toolbox create $cname || true

$run sudo dnf copr enable -y $copr_i3status_rs

$run sudo dnf install -y $dnf_sway $dnf_misc
