#!/bin/bash

set -euo pipefail

#
# Go (golang) environment
#
cname=go
run="toolbox run --container $cname"

dnf_misc=(
    golang
    golang-x-tools-gopls

    neovim
    fzf bat
    cmake # for telescope-fzf-native

    graphviz # "dot" etc.
)

set -x

toolbox create $cname || true

$run sudo dnf install -y "${dnf_misc[@]}"
