#!/bin/bash

set -euo pipefail

cname=gui
run="toolbox run --container $cname"

scripts_dir=$(readlink -e toolbox-gui.d)
run_scripts_from=$(which ,run-scripts-from)

packages=(
  fzf
  xdg-user-dirs
)

(
  set -x
  toolbox create $cname 2>/dev/null || true

  $run sudo dnf install -y "${packages[@]}"

  $run "$run_scripts_from" "$scripts_dir"
)
